// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: 3.95inch_test

#ifndef _3_95INCH_TEST_UI_H
#define _3_95INCH_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_3_95inch_png);    // assets/3.95inch.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/Temp.png
LV_IMG_DECLARE(ui_img_hum_png);    // assets/Hum.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets/CO2.png
LV_IMG_DECLARE(ui_img_tvoc_png);    // assets/TVOC.png
LV_IMG_DECLARE(ui_img_makerfabs3_png);    // assets/makerfabs3.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
